export interface StateUnclaimedProgram {
  code: string;
  name: string;
  agency: string;
  searchUrl: string;
  claimUrl: string;
  phone: string;
  minAmount: string;
  dormancyPeriod: string;
  propertyTypes: string[];
  description: string;
  tips: string;
}

export const STATE_UNCLAIMED_PROGRAMS: StateUnclaimedProgram[] = [
  {
    code: 'AL',
    name: 'Alabama',
    agency: 'Alabama State Treasurer — Unclaimed Property Division',
    searchUrl: 'https://unclaimedproperty.alabama.gov/',
    claimUrl: 'https://unclaimedproperty.alabama.gov/',
    phone: '(334) 242-7500',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance proceeds', 'Utility deposits', 'Wages', 'Stocks/dividends'],
    description: 'Alabama Treasury holds unclaimed property including bank accounts, insurance proceeds, utility deposits, and more.',
    tips: 'Search using maiden names and previous addresses. Alabama has no time limit to file a claim.',
  },
  {
    code: 'AK',
    name: 'Alaska',
    agency: 'Alaska Department of Revenue — Treasury Division',
    searchUrl: 'https://unclaimedproperty.alaska.gov/',
    claimUrl: 'https://unclaimedproperty.alaska.gov/',
    phone: '(907) 465-3726',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'PFD dividends', 'Insurance', 'Wages', 'Securities'],
    description: 'Alaska holds unclaimed property and Permanent Fund Dividends (PFD) that were undeliverable.',
    tips: 'Check for unclaimed PFD checks — many Alaskans have uncashed dividend payments.',
  },
  {
    code: 'AZ',
    name: 'Arizona',
    agency: 'Arizona Department of Revenue — Unclaimed Property Unit',
    searchUrl: 'https://azdor.gov/unclaimed-property',
    claimUrl: 'https://azdor.gov/unclaimed-property/how-claim-unclaimed-property',
    phone: '(877) 492-9957',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Utility deposits', 'Safe deposit boxes', 'Gift cards'],
    description: 'Arizona Department of Revenue manages unclaimed property including bank accounts, safe deposit boxes, and uncashed checks.',
    tips: 'Arizona holds over $1 billion in unclaimed property. Search variations of your name.',
  },
  {
    code: 'AR',
    name: 'Arkansas',
    agency: 'Arkansas Auditor of State — Unclaimed Property',
    searchUrl: 'https://www.claimitarkansas.org/',
    claimUrl: 'https://www.claimitarkansas.org/',
    phone: '(501) 682-6000',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility refunds', 'Stocks'],
    description: 'Arkansas Auditor holds unclaimed property with a 5-year dormancy period before escheatment.',
    tips: 'Arkansas uses claimitarkansas.org as their official search portal.',
  },
  {
    code: 'CA',
    name: 'California',
    agency: 'California State Controller — Unclaimed Property',
    searchUrl: 'https://www.sco.ca.gov/upd_msg.html',
    claimUrl: 'https://www.sco.ca.gov/upd_howto.html',
    phone: '(800) 992-4647',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Stocks', 'Wages', 'Safe deposit boxes', 'Utility refunds', 'Cashier checks'],
    description: 'California holds over $10 billion in unclaimed property — the largest program in the US. Managed by the State Controller.',
    tips: 'California has the most unclaimed property of any state. Search using all name variations, maiden names, and previous addresses.',
  },
  {
    code: 'CO',
    name: 'Colorado',
    agency: 'Colorado Department of the Treasury — Great Colorado Payback',
    searchUrl: 'https://colorado.findyourunclaimedproperty.com/',
    claimUrl: 'https://colorado.findyourunclaimedproperty.com/',
    phone: '(800) 825-2111',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Securities', 'Mineral rights'],
    description: 'Colorado\'s "Great Colorado Payback" program holds unclaimed property including mineral rights and royalty payments.',
    tips: 'Colorado has significant unclaimed mineral rights and oil/gas royalties. Check for deceased relatives too.',
  },
  {
    code: 'CT',
    name: 'Connecticut',
    agency: 'Connecticut Office of the Treasurer — Unclaimed Property',
    searchUrl: 'https://www.ctbiglist.com/',
    claimUrl: 'https://www.ctbiglist.com/',
    phone: '(860) 702-3050',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court deposits'],
    description: 'Connecticut uses CTBigList.com as their official unclaimed property search portal.',
    tips: 'Search at ctbiglist.com — Connecticut\'s dedicated unclaimed property portal.',
  },
  {
    code: 'DE',
    name: 'Delaware',
    agency: 'Delaware Department of Finance — Unclaimed Property',
    searchUrl: 'https://unclaimedproperty.delaware.gov/',
    claimUrl: 'https://unclaimedproperty.delaware.gov/',
    phone: '(302) 577-8782',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Corporate dividends', 'Wages', 'Gift cards'],
    description: 'Delaware is a major incorporation state, so many unclaimed corporate dividends and shares are held here.',
    tips: 'Many companies are incorporated in Delaware — check here even if you\'ve never lived in the state.',
  },
  {
    code: 'FL',
    name: 'Florida',
    agency: 'Florida Department of Financial Services — Unclaimed Property',
    searchUrl: 'https://www.fltreasurehunt.gov/',
    claimUrl: 'https://www.fltreasurehunt.gov/',
    phone: '(888) 258-2253',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Utility deposits', 'Safe deposit boxes', 'Wages', 'Court deposits'],
    description: 'Florida holds over $3 billion in unclaimed property through their "Florida Treasure Hunt" program.',
    tips: 'Florida is a top state for unclaimed property due to high population turnover. Search fltreasurehunt.gov.',
  },
  {
    code: 'GA',
    name: 'Georgia',
    agency: 'Georgia Department of Revenue — Unclaimed Property Program',
    searchUrl: 'https://dor.georgia.gov/unclaimed-property',
    claimUrl: 'https://dor.georgia.gov/unclaimed-property',
    phone: '(855) 329-2055',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility refunds', 'Securities'],
    description: 'Georgia Department of Revenue manages unclaimed property with over $1 billion held.',
    tips: 'Georgia transferred unclaimed property management from the Commissioner of Insurance to the Department of Revenue.',
  },
  {
    code: 'HI',
    name: 'Hawaii',
    agency: 'Hawaii Department of Budget and Finance — Unclaimed Property',
    searchUrl: 'https://hiupd.ehawaii.gov/hiupd/search.html',
    claimUrl: 'https://hiupd.ehawaii.gov/hiupd/search.html',
    phone: '(808) 586-1589',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court funds'],
    description: 'Hawaii is the only state not on MissingMoney.com — search directly through their state portal.',
    tips: 'Hawaii does NOT participate in MissingMoney.com. You must search their state site directly.',
  },
  {
    code: 'ID',
    name: 'Idaho',
    agency: 'Idaho State Tax Commission — Unclaimed Property',
    searchUrl: 'https://yourmoney.idaho.gov/',
    claimUrl: 'https://yourmoney.idaho.gov/',
    phone: '(208) 332-7700',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Mineral royalties', 'Utility deposits'],
    description: 'Idaho\'s "Your Money Idaho" portal lets you search and claim unclaimed property online.',
    tips: 'Idaho has mineral royalties and oil/gas payments that go unclaimed. Check for those specifically.',
  },
  {
    code: 'IL',
    name: 'Illinois',
    agency: 'Illinois State Treasurer — I-Cash',
    searchUrl: 'https://icash.illinoistreasurer.gov/',
    claimUrl: 'https://icash.illinoistreasurer.gov/',
    phone: '(217) 785-6998',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Safe deposit boxes', 'Stocks', 'Court deposits'],
    description: 'Illinois I-Cash program holds over $3.5 billion in unclaimed property — one of the largest state programs.',
    tips: 'Illinois is one of the top 5 states for unclaimed property. Search icash.illinoistreasurer.gov.',
  },
  {
    code: 'IN',
    name: 'Indiana',
    agency: 'Indiana Attorney General — Unclaimed Property Division',
    searchUrl: 'https://www.indianaunclaimed.gov/',
    claimUrl: 'https://www.indianaunclaimed.gov/',
    phone: '(866) 462-5246',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Securities'],
    description: 'Indiana Attorney General manages unclaimed property through indianaunclaimed.gov.',
    tips: 'Indiana has a 3-year dormancy period — shorter than many states. Check frequently.',
  },
  {
    code: 'IA',
    name: 'Iowa',
    agency: 'Iowa State Treasurer — Great Iowa Treasure Hunt',
    searchUrl: 'https://greatiowatreasurehunt.gov/',
    claimUrl: 'https://greatiowatreasurehunt.gov/',
    phone: '(515) 281-5368',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility refunds', 'Farm proceeds'],
    description: 'Iowa\'s "Great Iowa Treasure Hunt" holds unclaimed property including farm-related proceeds.',
    tips: 'Iowa has unclaimed farm proceeds and agricultural payments. Search using business names too.',
  },
  {
    code: 'KS',
    name: 'Kansas',
    agency: 'Kansas State Treasurer — Unclaimed Property Division',
    searchUrl: 'https://kansascash.ks.gov/',
    claimUrl: 'https://kansascash.ks.gov/',
    phone: '(800) 432-0386',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Oil/gas royalties'],
    description: 'Kansas holds unclaimed property through their KansasCash portal including oil and gas royalties.',
    tips: 'Kansas has significant unclaimed oil/gas royalties from mineral rights.',
  },
  {
    code: 'KY',
    name: 'Kentucky',
    agency: 'Kentucky State Treasury — Unclaimed Property',
    searchUrl: 'https://treasury.ky.gov/unclaimedproperty/',
    claimUrl: 'https://treasury.ky.gov/unclaimedproperty/',
    phone: '(800) 465-4722',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Coal/mineral royalties'],
    description: 'Kentucky Treasury holds unclaimed property including coal and mineral royalty payments.',
    tips: 'Kentucky has unclaimed coal royalties and mineral rights payments. Check for family members too.',
  },
  {
    code: 'LA',
    name: 'Louisiana',
    agency: 'Louisiana State Treasury — Unclaimed Property',
    searchUrl: 'https://www.latreasury.com/unclaimed-property/',
    claimUrl: 'https://www.latreasury.com/unclaimed-property/',
    phone: '(888) 925-4127',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Oil/gas royalties', 'Court deposits'],
    description: 'Louisiana Treasury manages unclaimed property including significant oil and gas royalties.',
    tips: 'Louisiana has major unclaimed oil/gas royalties from mineral rights in the Gulf region.',
  },
  {
    code: 'ME',
    name: 'Maine',
    agency: 'Maine State Treasurer — Unclaimed Property',
    searchUrl: 'https://maineunclaimedproperty.gov/',
    claimUrl: 'https://maineunclaimedproperty.gov/',
    phone: '(207) 624-7477',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility refunds', 'Court deposits'],
    description: 'Maine Treasurer holds unclaimed property with online search and claim filing.',
    tips: 'Maine has a 3-year dormancy period. Check for seasonal residents and vacation property refunds.',
  },
  {
    code: 'MD',
    name: 'Maryland',
    agency: 'Maryland Comptroller — Unclaimed Property',
    searchUrl: 'https://interactive.marylandtaxes.gov/Unclaimed/Default.aspx',
    claimUrl: 'https://interactive.marylandtaxes.gov/Unclaimed/Default.aspx',
    phone: '(410) 767-1700',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Tax refunds', 'Utility deposits'],
    description: 'Maryland Comptroller manages unclaimed property including uncashed state tax refund checks.',
    tips: 'Maryland has many unclaimed tax refund checks. Check if you\'ve ever filed MD taxes.',
  },
  {
    code: 'MA',
    name: 'Massachusetts',
    agency: 'Massachusetts State Treasurer — Unclaimed Property Division',
    searchUrl: 'https://findmassmoney.com/',
    claimUrl: 'https://findmassmoney.com/',
    phone: '(888) 344-6277',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Safe deposit boxes'],
    description: 'Massachusetts uses FindMassMoney.com to help residents search for unclaimed property.',
    tips: 'Search findmassmoney.com — Massachusetts\' dedicated unclaimed property portal.',
  },
  {
    code: 'MI',
    name: 'Michigan',
    agency: 'Michigan Department of Treasury — Unclaimed Property',
    searchUrl: 'https://unclaimedproperty.michigan.gov/',
    claimUrl: 'https://unclaimedproperty.michigan.gov/',
    phone: '(517) 636-5320',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Safe deposit boxes'],
    description: 'Michigan Treasury holds unclaimed property. Post-Rafaeli ruling, the state must return excess tax sale proceeds.',
    tips: 'After the Rafaeli Supreme Court decision, Michigan must return excess proceeds from tax sales.',
  },
  {
    code: 'MN',
    name: 'Minnesota',
    agency: 'Minnesota Department of Commerce — Unclaimed Property',
    searchUrl: 'https://mn.gov/commerce/consumers/your-money/find-missing-money/',
    claimUrl: 'https://mn.gov/commerce/consumers/your-money/find-missing-money/',
    phone: '(651) 539-1500',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Safe deposit boxes', 'Securities'],
    description: 'Minnesota Department of Commerce manages unclaimed property with online search.',
    tips: 'Minnesota has a short 3-year dormancy period. Check regularly for new listings.',
  },
  {
    code: 'MS',
    name: 'Mississippi',
    agency: 'Mississippi State Treasury — Unclaimed Property',
    searchUrl: 'https://treasury.ms.gov/unclaimed-property/',
    claimUrl: 'https://treasury.ms.gov/unclaimed-property/',
    phone: '(601) 359-3534',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Mineral royalties'],
    description: 'Mississippi Treasury holds unclaimed property with a 5-year dormancy period.',
    tips: 'Mississippi has unclaimed mineral and timber royalties. Search using business names too.',
  },
  {
    code: 'MO',
    name: 'Missouri',
    agency: 'Missouri State Treasurer — Show-Me Money',
    searchUrl: 'https://treasurer.mo.gov/unclaimedproperty/',
    claimUrl: 'https://treasurer.mo.gov/unclaimedproperty/',
    phone: '(573) 751-0840',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court funds'],
    description: 'Missouri\'s "Show-Me Money" program helps residents find and claim unclaimed property.',
    tips: 'Missouri calls their program "Show-Me Money." Claims over $25 may require notarization.',
  },
  {
    code: 'MT',
    name: 'Montana',
    agency: 'Montana Department of Revenue — Unclaimed Property',
    searchUrl: 'https://mtrevenue.gov/unclaimed-property/',
    claimUrl: 'https://mtrevenue.gov/unclaimed-property/',
    phone: '(406) 444-6900',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Mineral royalties', 'Utility deposits'],
    description: 'Montana Department of Revenue holds unclaimed property including mineral and mining royalties.',
    tips: 'Montana has unclaimed mining royalties and mineral rights payments.',
  },
  {
    code: 'NE',
    name: 'Nebraska',
    agency: 'Nebraska State Treasurer — Unclaimed Property',
    searchUrl: 'https://treasurer.nebraska.gov/up/',
    claimUrl: 'https://treasurer.nebraska.gov/up/',
    phone: '(877) 572-9688',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Farm proceeds'],
    description: 'Nebraska State Treasurer holds unclaimed property including agricultural and farm proceeds.',
    tips: 'Nebraska has unclaimed agricultural proceeds and commodity payments. Search for farm/business names.',
  },
  {
    code: 'NV',
    name: 'Nevada',
    agency: 'Nevada State Treasurer — Unclaimed Property',
    searchUrl: 'https://nevadatreasurer.gov/unclaimed-property/',
    claimUrl: 'https://nevadatreasurer.gov/unclaimed-property/',
    phone: '(702) 486-4140',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Casino winnings', 'Insurance', 'Wages', 'Utility deposits'],
    description: 'Nevada holds unclaimed property including uncashed casino winnings and gaming proceeds.',
    tips: 'Nevada has unclaimed casino winnings and gaming proceeds. Check if you\'ve ever gambled in NV.',
  },
  {
    code: 'NH',
    name: 'New Hampshire',
    agency: 'New Hampshire State Treasury — Unclaimed Property',
    searchUrl: 'https://www.treasury.nh.gov/unclaimed-property',
    claimUrl: 'https://www.treasury.nh.gov/unclaimed-property',
    phone: '(603) 271-2619',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court funds'],
    description: 'New Hampshire Treasury holds unclaimed property with free online search.',
    tips: 'New Hampshire has no income tax, but still holds unclaimed property from financial institutions.',
  },
  {
    code: 'NJ',
    name: 'New Jersey',
    agency: 'New Jersey Department of the Treasury — Unclaimed Property',
    searchUrl: 'https://www.unclaimedproperty.nj.gov/',
    claimUrl: 'https://www.unclaimedproperty.nj.gov/',
    phone: '(609) 292-9200',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Safe deposit boxes', 'Court deposits'],
    description: 'New Jersey Treasury holds over $4 billion in unclaimed property — one of the largest programs in the US.',
    tips: 'New Jersey is one of the top states for unclaimed property. High population density means lots of unclaimed funds.',
  },
  {
    code: 'NM',
    name: 'New Mexico',
    agency: 'New Mexico Taxation and Revenue Department — Unclaimed Property',
    searchUrl: 'https://www.tax.newmexico.gov/individuals/what-is-unclaimed-property/search-unclaimed-property/',
    claimUrl: 'https://www.tax.newmexico.gov/individuals/what-is-unclaimed-property/',
    phone: '(505) 827-0762',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Oil/gas royalties', 'Utility deposits'],
    description: 'New Mexico Taxation & Revenue manages unclaimed property including oil/gas royalties.',
    tips: 'New Mexico has significant unclaimed oil and gas royalty payments from mineral rights.',
  },
  {
    code: 'NY',
    name: 'New York',
    agency: 'New York Office of the State Comptroller — Unclaimed Funds',
    searchUrl: 'https://www.osc.ny.gov/unclaimed-funds',
    claimUrl: 'https://www.osc.ny.gov/unclaimed-funds',
    phone: '(800) 221-9311',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Court deposits', 'Securities', 'Safe deposit boxes'],
    description: 'New York holds over $17 billion in unclaimed funds — the largest state program. Managed by the State Comptroller.',
    tips: 'New York has the most unclaimed property of any state by dollar amount. Search using all name variations.',
  },
  {
    code: 'NC',
    name: 'North Carolina',
    agency: 'North Carolina Department of State Treasurer — Unclaimed Property',
    searchUrl: 'https://www.nccash.com/',
    claimUrl: 'https://www.nccash.com/',
    phone: '(919) 814-4000',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court funds'],
    description: 'North Carolina uses NCCash.com as their official unclaimed property search portal.',
    tips: 'Search at nccash.com — North Carolina\'s dedicated unclaimed property search portal.',
  },
  {
    code: 'ND',
    name: 'North Dakota',
    agency: 'North Dakota Department of Trust Lands — Unclaimed Property',
    searchUrl: 'https://land.nd.gov/unclaimed-property',
    claimUrl: 'https://land.nd.gov/unclaimed-property',
    phone: '(701) 328-2800',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Mineral royalties', 'Oil/gas payments'],
    description: 'North Dakota Department of Trust Lands manages unclaimed property including oil/gas royalties.',
    tips: 'North Dakota has major unclaimed oil and gas royalties from the Bakken formation.',
  },
  {
    code: 'OH',
    name: 'Ohio',
    agency: 'Ohio Department of Commerce — Unclaimed Funds',
    searchUrl: 'https://com.ohio.gov/unfd/',
    claimUrl: 'https://com.ohio.gov/unfd/',
    phone: '(614) 466-4433',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Safe deposit boxes'],
    description: 'Ohio Department of Commerce holds unclaimed funds with free online search and claim filing.',
    tips: 'Ohio has a large program with billions in unclaimed funds. Search using previous Ohio addresses.',
  },
  {
    code: 'OK',
    name: 'Oklahoma',
    agency: 'Oklahoma State Treasurer — Unclaimed Property',
    searchUrl: 'https://oklahoma.findyourunclaimedproperty.com/',
    claimUrl: 'https://oklahoma.findyourunclaimedproperty.com/',
    phone: '(405) 521-4273',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Oil/gas royalties', 'Mineral rights'],
    description: 'Oklahoma holds major unclaimed oil/gas royalties and mineral rights payments.',
    tips: 'Oklahoma has extensive unclaimed oil and gas royalties. Check for mineral rights owners.',
  },
  {
    code: 'OR',
    name: 'Oregon',
    agency: 'Oregon Department of State Lands — Unclaimed Property',
    searchUrl: 'https://unclaimed.oregon.gov/',
    claimUrl: 'https://unclaimed.oregon.gov/',
    phone: '(503) 378-3805',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Timber royalties'],
    description: 'Oregon Department of State Lands manages unclaimed property including timber-related proceeds.',
    tips: 'Oregon has unclaimed timber royalties and natural resource payments.',
  },
  {
    code: 'PA',
    name: 'Pennsylvania',
    agency: 'Pennsylvania Treasury — Unclaimed Property',
    searchUrl: 'https://www.patreasury.gov/unclaimed-property/',
    claimUrl: 'https://www.patreasury.gov/unclaimed-property/',
    phone: '(800) 222-2046',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Safe deposit boxes', 'Court deposits'],
    description: 'Pennsylvania Treasury holds over $4 billion in unclaimed property — one of the largest state programs.',
    tips: 'Pennsylvania is a top-5 state for unclaimed property. Search at patreasury.gov.',
  },
  {
    code: 'RI',
    name: 'Rhode Island',
    agency: 'Rhode Island Treasury — Unclaimed Property',
    searchUrl: 'https://findrimoney.com/',
    claimUrl: 'https://findrimoney.com/',
    phone: '(401) 462-7676',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court funds'],
    description: 'Rhode Island uses FindRIMoney.com as their official unclaimed property search portal.',
    tips: 'Search findrimoney.com — Rhode Island\'s dedicated portal.',
  },
  {
    code: 'SC',
    name: 'South Carolina',
    agency: 'South Carolina State Treasurer — Unclaimed Property',
    searchUrl: 'https://treasurer.sc.gov/unclaimed-property/',
    claimUrl: 'https://treasurer.sc.gov/unclaimed-property/',
    phone: '(803) 734-2101',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court deposits'],
    description: 'South Carolina Treasurer holds unclaimed property with online search and claim filing.',
    tips: 'South Carolina has a 5-year dormancy period. Check for military-related unclaimed property too.',
  },
  {
    code: 'SD',
    name: 'South Dakota',
    agency: 'South Dakota State Treasurer — Unclaimed Property',
    searchUrl: 'https://sdtreasurer.gov/unclaimed-property/',
    claimUrl: 'https://sdtreasurer.gov/unclaimed-property/',
    phone: '(605) 773-3378',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Farm proceeds'],
    description: 'South Dakota Treasurer manages unclaimed property including agricultural and farm proceeds.',
    tips: 'South Dakota is a major trust state — check for trust-related unclaimed property.',
  },
  {
    code: 'TN',
    name: 'Tennessee',
    agency: 'Tennessee Treasury — Unclaimed Property',
    searchUrl: 'https://treasury.tn.gov/Unclaimed-Property/',
    claimUrl: 'https://treasury.tn.gov/Unclaimed-Property/',
    phone: '(615) 741-6499',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court deposits'],
    description: 'Tennessee Treasury holds unclaimed property with free online search.',
    tips: 'Tennessee has no income tax on wages but still holds billions in unclaimed property.',
  },
  {
    code: 'TX',
    name: 'Texas',
    agency: 'Texas Comptroller of Public Accounts — Unclaimed Property',
    searchUrl: 'https://claimittexas.org/',
    claimUrl: 'https://claimittexas.org/',
    phone: '(800) 321-2274',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Oil/gas royalties', 'Safe deposit boxes', 'Court deposits'],
    description: 'Texas holds over $8 billion in unclaimed property through their ClaimItTexas.org portal — the second largest program.',
    tips: 'Texas is #2 in unclaimed property. Huge oil/gas royalties go unclaimed. Search claimittexas.org.',
  },
  {
    code: 'UT',
    name: 'Utah',
    agency: 'Utah State Treasurer — Unclaimed Property',
    searchUrl: 'https://mycash.utah.gov/',
    claimUrl: 'https://mycash.utah.gov/',
    phone: '(801) 715-3300',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Mineral royalties'],
    description: 'Utah uses MyCash.utah.gov as their official unclaimed property search portal.',
    tips: 'Search mycash.utah.gov — Utah\'s dedicated unclaimed property portal.',
  },
  {
    code: 'VT',
    name: 'Vermont',
    agency: 'Vermont State Treasurer — Unclaimed Property Division',
    searchUrl: 'https://www.vermonttreasurer.gov/content/unclaimed-property',
    claimUrl: 'https://www.vermonttreasurer.gov/content/unclaimed-property',
    phone: '(802) 828-2301',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court funds'],
    description: 'Vermont Treasurer holds unclaimed property with online search.',
    tips: 'Vermont has a short 3-year dormancy period and a relatively small but active program.',
  },
  {
    code: 'VA',
    name: 'Virginia',
    agency: 'Virginia Department of the Treasury — Unclaimed Property',
    searchUrl: 'https://vamoneysearch.org/',
    claimUrl: 'https://vamoneysearch.org/',
    phone: '(800) 468-1088',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court deposits', 'Military pay'],
    description: 'Virginia uses VAMoneySearch.org for unclaimed property searches. Includes military pay and benefits.',
    tips: 'Virginia has unclaimed military pay and benefits due to large military presence (Norfolk, Pentagon).',
  },
  {
    code: 'WA',
    name: 'Washington',
    agency: 'Washington Department of Revenue — Unclaimed Property',
    searchUrl: 'https://ucp.dor.wa.gov/',
    claimUrl: 'https://ucp.dor.wa.gov/',
    phone: '(360) 534-1502',
    minAmount: 'No minimum',
    dormancyPeriod: '3 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Safe deposit boxes'],
    description: 'Washington Department of Revenue manages unclaimed property with online search and claim.',
    tips: 'Washington has no income tax but holds billions in unclaimed property from financial institutions.',
  },
  {
    code: 'WV',
    name: 'West Virginia',
    agency: 'West Virginia State Treasurer — Unclaimed Property',
    searchUrl: 'https://www.wvtreasury.com/Unclaimed-Property/',
    claimUrl: 'https://www.wvtreasury.com/Unclaimed-Property/',
    phone: '(304) 558-5000',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Coal/mineral royalties', 'Utility deposits'],
    description: 'West Virginia Treasurer holds unclaimed property including coal and mineral royalty payments.',
    tips: 'West Virginia has unclaimed coal royalties and mineral rights payments. Check for heirs.',
  },
  {
    code: 'WI',
    name: 'Wisconsin',
    agency: 'Wisconsin State Treasurer — Unclaimed Property',
    searchUrl: 'https://missingmoney.com/en/property/search',
    claimUrl: 'https://statetreasurer.wi.gov/Pages/Home.aspx',
    phone: '(855) 375-2274',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Utility deposits', 'Court funds'],
    description: 'Wisconsin State Treasurer holds unclaimed property searchable through MissingMoney.com.',
    tips: 'Wisconsin primarily uses MissingMoney.com for searches. Check both portals.',
  },
  {
    code: 'WY',
    name: 'Wyoming',
    agency: 'Wyoming State Treasurer — Unclaimed Property',
    searchUrl: 'https://treasurer.wyo.gov/unclaimed-property/',
    claimUrl: 'https://treasurer.wyo.gov/unclaimed-property/',
    phone: '(307) 777-5590',
    minAmount: 'No minimum',
    dormancyPeriod: '5 years',
    propertyTypes: ['Bank accounts', 'Insurance', 'Wages', 'Oil/gas royalties', 'Mineral rights'],
    description: 'Wyoming Treasurer holds unclaimed property including oil, gas, and mineral royalty payments.',
    tips: 'Wyoming has major unclaimed mineral and oil/gas royalties. Check for trust-related property too.',
  },
];

export function getStateProgram(code: string): StateUnclaimedProgram | undefined {
  return STATE_UNCLAIMED_PROGRAMS.find(s => s.code === code);
}

export function getStateProgramByName(name: string): StateUnclaimedProgram | undefined {
  return STATE_UNCLAIMED_PROGRAMS.find(s => s.name.toLowerCase() === name.toLowerCase());
}
